version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "janstenpickle"
      - "catostrophe"
    labels:
      - "dependency-update"
