addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.5.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-github-actions"   % "0.15.0")
addSbtPlugin("io.shiftleft"              % "sbt-ci-release-early" % "2.0.44")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.1.1")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"      % "1.1.2")
