addSbtPlugin("org.scalameta"  % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"         % "0.5.2")
addSbtPlugin("com.github.sbt" % "sbt-github-actions"   % "0.24.0")
addSbtPlugin("io.shiftleft"   % "sbt-ci-release-early" % "2.0.46")
addSbtPlugin("com.github.sbt" % "sbt-dynver"           % "5.0.1")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin"      % "1.1.4")
