addSbtPlugin("org.scalameta"  % "sbt-scalafmt"         % "2.5.0")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"         % "0.5.0")
addSbtPlugin("com.codecommit" % "sbt-github-actions"   % "0.14.2")
addSbtPlugin("io.shiftleft"   % "sbt-ci-release-early" % "2.0.45")
addSbtPlugin("com.github.sbt" % "sbt-dynver"           % "5.0.1")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin"      % "1.1.3")
