name: Build & Release

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        scala-version:
          - "2.12.13"
          - "2.13.6"
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache ivy2
        uses: actions/cache@v2.1.5
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.5
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ ++${{ matrix.scala-version }} '; scalafmtCheckAll; scalafmtSbtCheck; compile; test' -J-Xms3G -J-Xmx6G -J-Xss4m

  release:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify[bot]'
    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Cache ivy2
        uses: actions/cache@v2.1.5
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.5
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: sonatype credentials
        run: |
          cat << EOF > ~/.sbt/sonatype_credentials
          realm=Sonatype Nexus Repository Manager
          host=oss.sonatype.org
          user=${{ secrets.SONATYPE_USER }}
          password=${{ secrets.SONATYPE_PASS }}
          EOF

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASS }}

      - name: scala build
        env:
          PGP_PASS: ${{ secrets.PGP_PASS }}
        run: |
          sbt -Dsona.user=${{ secrets.SONATYPE_USER }} -Dsona.pass=${{ secrets.SONATYPE_PASS }} -Dsbt.coursier.home=~/.sbt/coursier/ +releaseEarly sonatypeBundleRelease -J-Xms3G -J-Xmx6G -J-Xss4m
